In [1]:
using DataFrames, StatsBase 

Useful Functions

In [2]:
#function that calculates out-of-sample error
#w = parameter array fit to model
#model = function that fits a model on a dataset
#test_set = dataset being tested
function out_sample_error(w,model,test_set)
    test_size = size(test_set,1)
    model_X = model(test_set)[2]
    model_output = round(model_X*w)
    model_error = 0
    for i in 1:test_size
        if test_set[:Survived][i] != model_output[i]
            model_error = model_error + 1
        end
    end
    return model_error / test_size
end

#function that runs a bootstrap estimation on the training set
#model = function that fits a model on a dataset
#resample_num = number of samples
function bootstrap_estimate(model,training_data
    ;resample_num = 1000)
    w_bs = 0
    td_size = size(training_data,1)
    for i in 1:resample_num
        #randomly samples from training set
        train_sample = training_data[sample(1:td_size,round(Int,.5*td_size)), :] 
        #incrememts bootstrap parameter by parameter of new sample
        w_bs = w_bs + model(train_sample)[1]
    end
    #finds average parameter among trials
    w_bs = w_bs / resample_num
    return w_bs
end 

#function that partitions data into train and test sets,
#runs model on train and checks error on test
#model = function that fits a model on a dataset
#training_data = dataset to be partitioned and crossvalidated
#k = number of partitions 
function cross_validate(model, training_data;
    k = 5)
    error_cv = 0
    td_size = size(training_data,1)
    #size of 1 partition when they are k partitions 
    partition = round(Int,td_size / k)
    for i in 1:k
        #creates training and test sets for this iteration
        s = (i-1)*partition + 1 
        if i == k 
            f = td_size
        else
            f = i*partition
        end
        #test partition with size 1/kth of dataset
        round_test = training_data[s:f,:]
        round_train_1 = training_data[1:s-1,:]
        round_train_2 = training_data[f+1:td_size,:]
        #training partition
        round_train = [round_train_1;round_train_2]
        #w when model is run on training set
        round_w = model(round_train)[1]
        #error in w when model run on test set
        round_error = out_sample_error(round_w,model,round_test)
        error_cv = error_cv + round_error
    end
    #average error among partitions 
    error_cv = error_cv / k
    return error_cv
end

#helper function for split_data
function build_subset(index,data)
    subset = similar(data,0)
    for i in 1:length(index)
        new_row = DataArray(data[data[:x] .== index[i],:])
        push!(subset,new_row)
    end
    return subset
end 

#splits dataset into train and test sets
#splits data based on the discharge identifier column :x (integer)
#split_raio = ratio of training set size to entire dataset size
function split_data(data_set;split_ratio = .8)
    n = size(data_set,1)
    split = Int(round(split_ratio*n))
    rand_index = shuffle(data_set[:x])
    train_index = rand_index[1:split]
    test_index = rand_index[split + 1:n]
    train = build_subset(train_index,data_set)
    test = build_subset(test_index,data_set)
    return(train,test)
end 


split_data (generic function with 1 method)

Analysis

In [3]:
#import data
heart_attack = readtable("heart_attack.csv")

1072×50 DataFrames.DataFrame
│ Row  │ x       │ Health_Service_Area │ Hospital_County │
├──────┼─────────┼─────────────────────┼─────────────────┤
│ 1    │ 3577    │ "Western NY"        │ "Cattaraugus"   │
│ 2    │ 5411    │ "Western NY"        │ "Cattaraugus"   │
│ 3    │ 8169    │ "Western NY"        │ "Chautauqua"    │
│ 4    │ 9390    │ "Western NY"        │ "Chautauqua"    │
│ 5    │ 16311   │ "Western NY"        │ "Chautauqua"    │
│ 6    │ 17014   │ "Western NY"        │ "Chautauqua"    │
│ 7    │ 17754   │ "Western NY"        │ "Chautauqua"    │
│ 8    │ 19217   │ "Western NY"        │ "Chautauqua"    │
│ 9    │ 21080   │ "Western NY"        │ "Erie"          │
│ 10   │ 21508   │ "Western NY"        │ "Erie"          │
│ 11   │ 21640   │ "Western NY"        │ "Erie"          │
⋮
│ 1061 │ 2519026 │ "Long Island"       │ "Suffolk"       │
│ 1062 │ 2527331 │ "Long Island"       │ "Suffolk"       │
│ 1063 │ 2532210 │ "Long Island"       │ "Suffolk"       │
│ 1064 │ 2535046 │ "Long Island"       │ "Suffolk"       │
│ 1065 │ 2535333 │ "Long Island"       │ "Suffolk"       │
│ 1066 │ 2537506 │ "Long Island"       │ "Suffolk"       │
│ 1067 │ 2538641 │ "Long Island"       │ "Suffolk"       │
│ 1068 │ 2539035 │ "Long Island"       │ "Suffolk"       │
│ 1069 │ 2540093 │ "Long Island"       │ "Suffolk"       │
│ 1070 │ 2542897 │ "Long Island"       │ "Suffolk"       │
│ 1071 │ 2543672 │ "Long Island"       │ "Suffolk"       │
│ 1072 │ 2544724 │ "Long Island"       │ "Suffolk"       │

│ Row  │ Operating_Certificate_Number │ Facility_Id │
├──────┼──────────────────────────────┼─────────────┤
│ 1    │ 401001                       │ 66          │
│ 2    │ 401001                       │ 66          │
│ 3    │ 601000                       │ 98          │
│ 4    │ 601000                       │ 98          │
│ 5    │ 602001                       │ 103         │
│ 6    │ 602001                       │ 103         │
│ 7    │ 602001                       │ 103         │
│ 8    │ 427000                       │ 114         │
│ 9    │ 1401014                      │ 207         │
│ 10   │ 1401014                      │ 207         │
│ 11   │ 1401014                      │ 207         │
⋮
│ 1061 │ 5154001                      │ 925         │
│ 1062 │ 5155000                      │ 938         │
│ 1063 │ 5157003                      │ 943         │
│ 1064 │ 5157003                      │ 943         │
│ 1065 │ 5157003                      │ 943         │
│ 1066 │ 5157003                      │ 943         │
│ 1067 │ 5157003                      │ 943         │
│ 1068 │ 5157003                      │ 943         │
│ 1069 │ 5157003                      │ 943         │
│ 1070 │ 5157003                      │ 943         │
│ 1071 │ 5157003                      │ 943         │
│ 1072 │ 5157003                      │ 943         │

│ Row  │ Facility_Name                            │ Age_Group     │
├──────┼──────────────────────────────────────────┼───────────────┤
│ 1    │ "Olean General Hospital"                 │ "70 or Older" │
│ 2    │ "Olean General Hospital"                 │ "18 to 29"    │
│ 3    │ "Brooks Memorial Hospital"               │ "70 or Older" │
│ 4    │ "Brooks Memorial Hospital"               │ "70 or Older" │
│ 5    │ "Woman's Christian Association"          │ "50 to 69"    │
│ 6    │ "Woman's Christian Association"          │ "70 or Older" │
│ 7    │ "Woman's Christian Association"          │ "70 or Older" │
│ 8    │ "TLC Health Network Lake Shore Hospital" │ "70 or Older" │
│ 9    │ "Buffalo General Hospital"               │ "50 to 69"    │
│ 10   │ "Buffalo General Hospital"               │ "70 or Older" │
│ 11   │ "Buffalo General Hospital"               │ "70 or Older" │
⋮
│ 1061 │ "Good Samaritan Hospital Medical Center" │ "50 to 69"    │
│ 1062 │ "Peconic Bay Medical Center"             │ "70 or Older" │
│ 1063 │ "St Catherine of Siena Hospital"         │ "50 to 69"    │
│ 1064 │ "St Catherine of Siena Hospital"         

Data Cleaning

In [4]:
#hospital stays with length > 120 days labeled as "120 +"
#change these to length 120
heart_attack[heart_attack[:Length_of_Stay] .== "120 +",12] = "120"

#convert length of stay value to float
heart_attack[:Length_of_Stay] = float(heart_attack[:Length_of_Stay])

1072-element Array{Float64,1}:
  9.0
  2.0
  1.0
  2.0
  5.0
  2.0
  4.0
  1.0
  3.0
  3.0
 47.0
  6.0
  4.0
  ⋮  
  6.0
 21.0
  5.0
  1.0
  1.0
  1.0
  2.0
  1.0
  2.0
 20.0
 21.0
  1.0

Split Into Train and Test

In [5]:
#only looking at NYC hospital data
NYC_data = heart_attack[heart_attack[:Health_Service_Area] .== "New York City",:]
train = split_data(NYC_data)[1]
test = split_data(NYC_data)[2]

90×50 DataFrames.DataFrame
│ Row │ x       │ Health_Service_Area │ Hospital_County │
├─────┼─────────┼─────────────────────┼─────────────────┤
│ 1   │ 1604997 │ "New York City"     │ "Manhattan"     │
│ 2   │ 1903831 │ "New York City"     │ "Queens"        │
│ 3   │ 2124919 │ "New York City"     │ "Richmond"      │
│ 4   │ 1284650 │ "New York City"     │ "Kings"         │
│ 5   │ 1163948 │ "New York City"     │ "Bronx"         │
│ 6   │ 1782937 │ "New York City"     │ "Manhattan"     │
│ 7   │ 1403716 │ "New York City"     │ "Kings"         │
│ 8   │ 1024361 │ "New York City"     │ "Bronx"         │
│ 9   │ 1869177 │ "New York City"     │ "Manhattan"     │
│ 10  │ 1248820 │ "New York City"     │ "Kings"         │
│ 11  │ 2141427 │ "New York City"     │ "Richmond"      │
⋮
│ 79  │ 1327939 │ "New York City"     │ "Kings"         │
│ 80  │ 1469466 │ "New York City"     │ "Manhattan"     │
│ 81  │ 1950354 │ "New York City"     │ "Queens"        │
│ 82  │ 2094746 │ "New York City"     │ "Queens"        │
│ 83  │ 1310605 │ "New York City"     │ "Kings"         │
│ 84  │ 1818943 │ "New York City"     │ "Manhattan"     │
│ 85  │ 1261829 │ "New York City"     │ "Kings"         │
│ 86  │ 1213442 │ "New York City"     │ "Kings"         │
│ 87  │ 1069109 │ "New York City"     │ "Bronx"         │
│ 88  │ 2032215 │ "New York City"     │ "Queens"        │
│ 89  │ 1179964 │ "New York City"     │ "Kings"         │
│ 90  │ 1095141 │ "New York City"     │ "Bronx"         │

│ Row │ Operating_Certificate_Number │ Facility_Id │
├─────┼──────────────────────────────┼─────────────┤
│ 1   │ 7002017                      │ 1450        │
│ 2   │ 7003000                      │ 1626        │
│ 3   │ 7004010                      │ 1738        │
│ 4   │ 7001019                      │ 1304        │
│ 5   │ 7000006                      │ 3058        │
│ 6   │ 7002053                      │ 1463        │
│ 7   │ 7001035                      │ 1318        │
│ 8   │ 7000006                      │ 1169        │
│ 9   │ 7002032                      │ 1469        │
│ 10  │ 7001016                      │ 1301        │
│ 11  │ 7004003                      │ 1740        │
⋮
│ 79  │ 7001020                      │ 1305        │
│ 80  │ 7002000                      │ 1437        │
│ 81  │ 7003003                      │ 1629        │
│ 82  │ 7002024                      │ 1639        │
│ 83  │ 7001020                      │ 1305        │
│ 84  │ 7002054                      │ 1464        │
│ 85  │ 7001037                      │ 1302        │
│ 86  │ 7001008                      │ 1293        │
│ 87  │ 7000008                      │ 1172        │
│ 88  │ 7001024                      │ 1635        │
│ 89  │ 7001002                      │ 1286        │
│ 90  │ 7000014                      │ 1176        │

│ Row │ Facility_Name                                                          │
├─────┼────────────────────────────────────────────────────────────────────────┤
│ 1   │ "Lenox Hill Hospital"                                                  │
│ 2   │ "Elmhurst Hospital Center"                                             │
│ 3   │ "Richmond University Medical Center"                                   │
│ 4   │ "NYU Lutheran Medical Center"                                          │
│ 5   │ "Montefiore Med Center - Jack D Weiler Hosp of A Einstein College Div" │
│ 6   │ "NYU Hospitals Center"                                                 │
│ 7   │ "Wyckoff Heights Medical Center"                                       │
│ 8   │ "Montefiore Medical Center - Henry & Lucy Moses Div"                   │
│ 9   │ "Mount Sinai St. Lukes"                                                │
│ 10  │ "Kings County Hospital Center"                                         │
│ 11  │ "Staten Island University Hosp-North"                                  │
⋮
│ 79  │ "Maimonides Medical Center"                                            │
│ 80  │ "New York Downtown Hospital"                    

Fit Models on Training Data

In [6]:
#MODEL ONE
#conditions on severity of illness and length of stay
function model_one(training_data)
    td_size = size(training_data,1)
    X = [training_data[:APR_Severity_of_Illness_Code].data training_data[:Length_of_Stay] ones(td_size)]
    y = training_data[:Survived].data
    w = X\y
    return (w,X)
end 

#MODEL TWO
#conditions on severity of illness, length of stay, and gender
function model_two(training_data)
    td_size = size(training_data,1)
    X = [training_data[:APR_Severity_of_Illness_Code].data training_data[:Length_of_Stay] training_data[:Male] ones(td_size)]
    y = training_data[:Survived].data
    w = X\y
    return (w,X)
end 

#MODEL THREE
#conditions on severity of illness, length of stay, gender, and age
function model_three(training_data)
    td_size = size(training_data,1)
    #binary value, if age is >= 70
    X = [training_data[:APR_Severity_of_Illness_Code].data training_data[:Length_of_Stay] training_data[:Male] training_data[:old70] ones(td_size)]
    y = training_data[:Survived].data
    w = X\y
    return (w,X)
end 

model_three (generic function with 1 method)

In [7]:
#parameters w for each model
w1 = model_one(train)[1]
w2 = model_two(train)[1]
w3 = model_three(train)[1]

5-element Array{Float64,1}:
 -0.261695 
  0.0214423
  0.165245 
 -0.168826 
  1.07584  

Cross Validation of Models

In [8]:
@show cross_validate(model_one, train)
@show cross_validate(model_two, train) 
@show cross_validate(model_three, train) 

cross_validate(model_one,train) = 0.22273082942097028
cross_validate(model_two,train) = 0.20320813771517998
cross_validate(model_three,train) = 0.18928012519561815


0.18928012519561815

Bootstrap Estimate for Models

In [9]:
w1_bs = bootstrap_estimate(model_one,train)
w2_bs = bootstrap_estimate(model_two,train)
w3_bs = bootstrap_estimate(model_three,train)

5-element Array{Float64,1}:
 -0.263623 
  0.0224991
  0.163289 
 -0.165949 
  1.07377  

Check Model Performance on Validation Set

In [10]:
@show out_sample_error(w1,model_one,test)
@show out_sample_error(w1_bs,model_one,test)
@show out_sample_error(w2,model_two,test)
@show out_sample_error(w2_bs,model_two,test)
@show out_sample_error(w3,model_three,test)
@show out_sample_error(w3_bs,model_three,test)

out_sample_error(w1,model_one,test) = 0.16666666666666666
out_sample_error(w1_bs,model_one,test) = 0.16666666666666666
out_sample_error(w2,model_two,test) = 0.1
out_sample_error(w2_bs,model_two,test) = 0.1111111111111111
out_sample_error(w3,model_three,test) = 0.12222222222222222
out_sample_error(w3_bs,model_three,test) = 0.13333333333333333


0.13333333333333333