In [1]:
using DataFrames, StatsBase 

Useful Functions

In [2]:
#model is model_function
function out_sample_error(w,model,test_set)
    test_size = size(test_set,1)
    model_X = model(test_set)[2]
    model_output = round(model_X*w)
    model_error = 0
    for i in 1:test_size
        if test_set[:Survived][i] != model_output[i]
            model_error = model_error + 1
        end
    end
    return model_error / test_size
end

#model is a model function
function bootstrap_estimate(model,training_data
    ;resample_num = 1000)
    w_bs = 0
    td_size = size(training_data,1)
    for i in 1:resample_num
        train_sample = training_data[sample(1:td_size,round(Int,.5*td_size)), :] 
        w_bs = w_bs + model(train_sample)[1]
    end
    w_bs = w_bs / resample_num
    return w_bs
end 

#model is a model function
function cross_validate(model, training_data;
    k = 5)
    error_cv = 0
    td_size = size(training_data,1)
    partition = round(Int,td_size / k)
    for i in 1:k
        #creates training and test sets for this iteration
        s = (i-1)*partition + 1 
    if i == k 
            f = td_size
    else
        f = i*partition
    end
        round_test = training_data[s:f,:]
        round_train_1 = training_data[1:s-1,:]
        round_train_2 = training_data[f+1:td_size,:]
        round_train = [round_train_1;round_train_2]
        round_w = model(round_train)[1]
        round_error = out_sample_error(round_w,model,round_test)
        error_cv = error_cv + round_error
    end
    error_cv = error_cv / k
    return error_cv
end

#helper function for split_data
function build_subset(index,data)
    subset = similar(data,0)
    for i in 1:length(index)
        new_row = DataArray(data[data[:x] .== index[i],:])
        push!(subset,new_row)
    end
    return subset
end 

#splits data based on the discharge identifier column :x (integer)
function split_data(data_set;split_ratio = .8)
    n = size(data_set,1)
    split = Int(round(split_ratio*n))
    rand_index = shuffle(data_set[:x])
    train_index = rand_index[1:split]
    test_index = rand_index[split + 1:n]

    train = build_subset(train_index,data_set)
    test = build_subset(test_index,data_set)
    return(train,test)
end 


split_data (generic function with 1 method)

Analysis

In [3]:
heart_attack = readtable("heart_attack.csv")

1072×50 DataFrames.DataFrame
│ Row  │ x       │ Health_Service_Area │ Hospital_County │
├──────┼─────────┼─────────────────────┼─────────────────┤
│ 1    │ 3577    │ "Western NY"        │ "Cattaraugus"   │
│ 2    │ 5411    │ "Western NY"        │ "Cattaraugus"   │
│ 3    │ 8169    │ "Western NY"        │ "Chautauqua"    │
│ 4    │ 9390    │ "Western NY"        │ "Chautauqua"    │
│ 5    │ 16311   │ "Western NY"        │ "Chautauqua"    │
│ 6    │ 17014   │ "Western NY"        │ "Chautauqua"    │
│ 7    │ 17754   │ "Western NY"        │ "Chautauqua"    │
│ 8    │ 19217   │ "Western NY"        │ "Chautauqua"    │
│ 9    │ 21080   │ "Western NY"        │ "Erie"          │
│ 10   │ 21508   │ "Western NY"        │ "Erie"          │
│ 11   │ 21640   │ "Western NY"        │ "Erie"          │
⋮
│ 1061 │ 2519026 │ "Long Island"       │ "Suffolk"       │
│ 1062 │ 2527331 │ "Long Island"       │ "Suffolk"       │
│ 1063 │ 2532210 │ "Long Island"       │ "Suffolk"       │
│ 1064 │ 2535046 │ "Long Island"       │ "Suffolk"       │
│ 1065 │ 2535333 │ "Long Island"       │ "Suffolk"       │
│ 1066 │ 2537506 │ "Long Island"       │ "Suffolk"       │
│ 1067 │ 2538641 │ "Long Island"       │ "Suffolk"       │
│ 1068 │ 2539035 │ "Long Island"       │ "Suffolk"       │
│ 1069 │ 2540093 │ "Long Island"       │ "Suffolk"       │
│ 1070 │ 2542897 │ "Long Island"       │ "Suffolk"       │
│ 1071 │ 2543672 │ "Long Island"       │ "Suffolk"       │
│ 1072 │ 2544724 │ "Long Island"       │ "Suffolk"       │

│ Row  │ Operating_Certificate_Number │ Facility_Id │
├──────┼──────────────────────────────┼─────────────┤
│ 1    │ 401001                       │ 66          │
│ 2    │ 401001                       │ 66          │
│ 3    │ 601000                       │ 98          │
│ 4    │ 601000                       │ 98          │
│ 5    │ 602001                       │ 103         │
│ 6    │ 602001                       │ 103         │
│ 7    │ 602001                       │ 103         │
│ 8    │ 427000                       │ 114         │
│ 9    │ 1401014                      │ 207         │
│ 10   │ 1401014                      │ 207         │
│ 11   │ 1401014                      │ 207         │
⋮
│ 1061 │ 5154001                      │ 925         │
│ 1062 │ 5155000                      │ 938         │
│ 1063 │ 5157003                      │ 943         │
│ 1064 │ 5157003                      │ 943         │
│ 1065 │ 5157003                      │ 943         │
│ 1066 │ 5157003                      │ 943         │
│ 1067 │ 5157003                      │ 943         │
│ 1068 │ 5157003                      │ 943         │
│ 1069 │ 5157003                      │ 943         │
│ 1070 │ 5157003                      │ 943         │
│ 1071 │ 5157003                      │ 943         │
│ 1072 │ 5157003                      │ 943         │

│ Row  │ Facility_Name                            │ Age_Group     │
├──────┼──────────────────────────────────────────┼───────────────┤
│ 1    │ "Olean General Hospital"                 │ "70 or Older" │
│ 2    │ "Olean General Hospital"                 │ "18 to 29"    │
│ 3    │ "Brooks Memorial Hospital"               │ "70 or Older" │
│ 4    │ "Brooks Memorial Hospital"               │ "70 or Older" │
│ 5    │ "Woman's Christian Association"          │ "50 to 69"    │
│ 6    │ "Woman's Christian Association"          │ "70 or Older" │
│ 7    │ "Woman's Christian Association"          │ "70 or Older" │
│ 8    │ "TLC Health Network Lake Shore Hospital" │ "70 or Older" │
│ 9    │ "Buffalo General Hospital"               │ "50 to 69"    │
│ 10   │ "Buffalo General Hospital"               │ "70 or Older" │
│ 11   │ "Buffalo General Hospital"               │ "70 or Older" │
⋮
│ 1061 │ "Good Samaritan Hospital Medical Center" │ "50 to 69"    │
│ 1062 │ "Peconic Bay Medical Center"             │ "70 or Older" │
│ 1063 │ "St Catherine of Siena Hospital"         │ "50 to 69"    │
│ 1064 │ "St Catherine of Siena Hospital"         

Data Cleaning

In [4]:
heart_attack[heart_attack[:Length_of_Stay] .== "120 +",12] = "120"
heart_attack[:Length_of_Stay] = float(heart_attack[:Length_of_Stay])

1072-element Array{Float64,1}:
  9.0
  2.0
  1.0
  2.0
  5.0
  2.0
  4.0
  1.0
  3.0
  3.0
 47.0
  6.0
  4.0
  ⋮  
  6.0
 21.0
  5.0
  1.0
  1.0
  1.0
  2.0
  1.0
  2.0
 20.0
 21.0
  1.0

Split into train and test

In [5]:
#LI_data = heart_attack[heart_attack[:Health_Service_Area] .== "Long Island",:]
NYC_data = heart_attack[heart_attack[:Health_Service_Area] .== "New York City",:]
train = split_data(NYC_data)[1]
test = split_data(NYC_data)[2]

90×50 DataFrames.DataFrame
│ Row │ x       │ Health_Service_Area │ Hospital_County │
├─────┼─────────┼─────────────────────┼─────────────────┤
│ 1   │ 1437432 │ "New York City"     │ "Kings"         │
│ 2   │ 1749073 │ "New York City"     │ "Manhattan"     │
│ 3   │ 1376960 │ "New York City"     │ "Kings"         │
│ 4   │ 2089898 │ "New York City"     │ "Queens"        │
│ 5   │ 978950  │ "New York City"     │ "Bronx"         │
│ 6   │ 980106  │ "New York City"     │ "Bronx"         │
│ 7   │ 1024361 │ "New York City"     │ "Bronx"         │
│ 8   │ 1916754 │ "New York City"     │ "Queens"        │
│ 9   │ 1604997 │ "New York City"     │ "Manhattan"     │
│ 10  │ 2155828 │ "New York City"     │ "Richmond"      │
│ 11  │ 1296347 │ "New York City"     │ "Kings"         │
⋮
│ 79  │ 1326175 │ "New York City"     │ "Kings"         │
│ 80  │ 1471205 │ "New York City"     │ "Manhattan"     │
│ 81  │ 1726256 │ "New York City"     │ "Manhattan"     │
│ 82  │ 1923708 │ "New York City"     │ "Queens"        │
│ 83  │ 1179215 │ "New York City"     │ "Kings"         │
│ 84  │ 2149327 │ "New York City"     │ "Richmond"      │
│ 85  │ 1257918 │ "New York City"     │ "Kings"         │
│ 86  │ 2109292 │ "New York City"     │ "Richmond"      │
│ 87  │ 1326639 │ "New York City"     │ "Kings"         │
│ 88  │ 1882109 │ "New York City"     │ "Manhattan"     │
│ 89  │ 1473003 │ "New York City"     │ "Manhattan"     │
│ 90  │ 1954538 │ "New York City"     │ "Queens"        │

│ Row │ Operating_Certificate_Number │ Facility_Id │
├─────┼──────────────────────────────┼─────────────┤
│ 1   │ 7001037                      │ 1320        │
│ 2   │ 7002054                      │ 1458        │
│ 3   │ 7001021                      │ 1306        │
│ 4   │ 7002024                      │ 1639        │
│ 5   │ 7000002                      │ 1165        │
│ 6   │ 7000002                      │ 1165        │
│ 7   │ 7000006                      │ 1169        │
│ 8   │ 7003000                      │ 1626        │
│ 9   │ 7002017                      │ 1450        │
│ 10  │ 7004003                      │ 1740        │
│ 11  │ 7001019                      │ 1304        │
⋮
│ 79  │ 7001020                      │ 1305        │
│ 80  │ 7002000                      │ 1437        │
│ 81  │ 7002054                      │ 1458        │
│ 82  │ 7003000                      │ 1626        │
│ 83  │ 7001002                      │ 1286        │
│ 84  │ 7004003                      │ 1740        │
│ 85  │ 7001037                      │ 1302        │
│ 86  │ 7004010                      │ 1738        │
│ 87  │ 7001020                      │ 1305        │
│ 88  │ 7002032                      │ 1469        │
│ 89  │ 7002000                      │ 1437        │
│ 90  │ 7003003                      │ 1629        │

│ Row │ Facility_Name                                                    │
├─────┼──────────────────────────────────────────────────────────────────┤
│ 1   │ "University Hospital of Brooklyn"                                │
│ 2   │ "New York Presbyterian Hospital - New York Weill Cornell Center" │
│ 3   │ "New York Methodist Hospital"                                    │
│ 4   │ "Mount Sinai Hospital - Mount Sinai Hospital of Queens"          │
│ 5   │ "Jacobi Medical Center"                                          │
│ 6   │ "Jacobi Medical Center"                                          │
│ 7   │ "Montefiore Medical Center - Henry & Lucy Moses Div"             │
│ 8   │ "Elmhurst Hospital Center"                                       │
│ 9   │ "Lenox Hill Hospital"                                            │
│ 10  │ "Staten Island University Hosp-North"                            │
│ 11  │ "NYU Lutheran Medical Center"                                    │
⋮
│ 79  │ "Maimonides Medical Center"                                      │
│ 80  │ "New York Downtown Hospital"                                     │
│ 81  │ "New York Presbyterian Hospital - New York Weill Cornell 

Fit models on training data

In [6]:
function model_one(training_data)
    td_size = size(training_data,1)
    X = [training_data[:APR_Severity_of_Illness_Code].data training_data[:Length_of_Stay] ones(td_size)]
    y = training_data[:Survived].data
    w = X\y
    return (w,X)
end 

function model_two(training_data)
    td_size = size(training_data,1)
    X = [training_data[:APR_Severity_of_Illness_Code].data training_data[:Length_of_Stay] training_data[:Male] ones(td_size)]
    y = training_data[:Survived].data
    w = X\y
    return (w,X)
end 

function model_three(training_data)
    td_size = size(training_data,1)
    X = [training_data[:APR_Severity_of_Illness_Code].data training_data[:Length_of_Stay] training_data[:Male] training_data[:old70] ones(td_size)]
    y = training_data[:Survived].data
    w = X\y
    return (w,X)
end 

w1 = model_one(train)[1]
w2 = model_two(train)[1]
w3 = model_three(train)[1]



5-element Array{Float64,1}:
 -0.263324 
  0.0212358
  0.171302 
 -0.177788 
  1.07332  

cross validation of models

In [7]:
@show cross_validate(model_one, train)
@show cross_validate(model_two, train) 
@show cross_validate(model_three, train) 

cross_validate(model_one,train) = 0.22836463223787168
cross_validate(model_two,train) = 0.1949530516431925
cross_validate(model_three,train) = 0.19769170579029732


0.19769170579029732

Bootstrap estimate for models

In [8]:
w1_bs = bootstrap_estimate(model_one,train)
w2_bs = bootstrap_estimate(model_two,train)
w3_bs = bootstrap_estimate(model_three,train)

5-element Array{Float64,1}:
 -0.266392 
  0.0224102
  0.169598 
 -0.175578 
  1.07726  

Check model performance on validation set

In [9]:
@show out_sample_error(w1,model_one,test)
@show out_sample_error(w1_bs,model_one,test)
@show out_sample_error(w2,model_two,test)
@show out_sample_error(w2_bs,model_two,test)
@show out_sample_error(w3,model_three,test)
@show out_sample_error(w3_bs,model_three,test)

out_sample_error(w1,model_one,test) = 0.25555555555555554
out_sample_error(w1_bs,model_one,test) = 0.2111111111111111
out_sample_error(w2,model_two,test) = 0.13333333333333333
out_sample_error(w2_bs,model_two,test) = 0.13333333333333333
out_sample_error(w3,model_three,test) = 0.14444444444444443
out_sample_error(w3_bs,model_three,test) = 0.15555555555555556


0.15555555555555556

Things to add: try adding regulizers to some models/generalize model making process
Ways to measure model error in terms of bias and variance 